### ISSUE TITLE
Entitas doesn't work

### ISSUE THREAD

**Issue by heavyfront** [sschmid/Entitas#1059]
Hello. After i install entitas from asset store like you did in tutorial, i press generate and see this error
![image](https://user-images.githubusercontent.com/111512372/226460281-fce0a28f-2053-472b-9449-04c8f3b3df69.png)

**Comment by heavyfront** [comment]
Translation of second part of this error - The requested fetch is not possible for a file with an open in-use section.

**Comment by sschmid** [comment]
@heavyfront I recommend getting the latest Entitas version from the GitHub release instead of Unity Asset store:

https://github.com/sschmid/Entitas/releases

For reference, you can have a look at Match-One, where I installed Entitas.zip to `Assets/Entitas`, and Jenny.zip to outside of the Assets folder `./Jenny`

https://github.com/sschmid/Match-One
