### ISSUE TITLE
Warning: No script asset for GameObjectSelectionItem

### ISSUE THREAD

**Issue by thygrrr** [sschmid/Entitas#680]
Whenever I navigate through the visual debugging / inspection hierarchy that Entitas provides, my Unity 2018.1.0b13 console gets spammed with these warnings for every click.

![Warning](https://i.imgur.com/hPZnVP0.png)

I can't discern the piece of code that is responsible at this time, will update this issue if I find something. Apart from the text, the warning has no additional info.

**Comment by BarbaricWizard** [comment]
Just started getting this error myself, and apparently it's something corrupted in the **currently open Animation window**.  It only happens when clicking on **GameObjects containing Animators while the Animation window is active in the Editor**.  I've yet to determine if there is something wrong with my animations that might be broken.  I was working on **changing pre-existing animations** in my last session prior to when I started getting this error, so there could definitely be broken animations still in one of my controllers.

**Comment by BarbaricWizard** [comment]
It would seem it is having trouble finding the following:

 https://github.com/Unity-Technologies/UnityCsReference/blob/master/Editor/Mono/Animation/AnimationWindow/GameObjectSelectionItem.cs

I'm thinking that maybe they changed this either into or from being a ScriptableObject due to the nature of the error message.

**Comment by exlineo** [comment]
In my project, the error came from transition between animations and 'Any State' state. You can see it in live in the Animator window in play mode.
