### ISSUE TITLE
Throw exception when creating more than 1 unique entity

### ISSUE THREAD

**Issue by sschmid** [sschmid/Entitas#763]
`context.isPaused = true;` is the generated api for [Unique] components.

```csharp
var e = context.CreateEntity();
e.isPaused = true; // currently works
```

The code above should throw an exception to enforce unique entities

**Comment by FNGgames** [comment]
I dont think you should throw there unless the unique entity already exists. It would break a ton of my code.

I like to create a unique entity to hold several other components, e.g. a settings entity with several non-unique components attached as the actual settings data. This way i can have easy access to lots of data through `context.settingsEntity.settingA.value` but also get the benefit of reactive systems and groups that trigger when certain combinations of these components are added or removed. I use this extensively for scene management, input, etc, where i need reactive systems to be able to trigger on combinations of components on the same entity but i also want the benefit of a context-level reference to the entity.

Does that make sense?

**Comment by sschmid** [comment]
Clarification:
`e.isPaused = true` should only throw, if there is an entity with this component already

**Comment by ethankennerly** [comment]
I share this concern about enforcing unique components in order to avoid having to do a query if other entities are already applying the not-necessarily unique component.

In the case of a unique component, have you considered removing the generated API for adding and removing a component to an entity?

In this example, do not generate `e.isPaused` property.

Instead, the context already has `context.isPaused` property.

And it already has `context.pausedEntity` entity.

As a user, I would rather not have an API than have an API that punishes me for using it.

Since the context has a way to add the component and for accessing the entity, all the valid use cases are supported, and none of the invalid use cases are left as traps for a user to stumble into.

**Comment by sschmid** [comment]
I'll take it back :D
This will stay valid and won't throw

```csharp
e.isPaused = true;
e.isPaused = true;
```
