### ISSUE TITLE
Is Jenny only sold in the unity store?

### ISSUE THREAD

**Issue by LywOPUS** [sschmid/Entitas#773]
Hi,

I have an idea ；
There is no doubt that Jenny is really good to use.
![2018-08-21 12 49 33](https://user-images.githubusercontent.com/10131887/44475608-0d045f00-a668-11e8-81af-32c8a77664be.png) （is Jenny a cat？🤔）
but，
If one day I bought a new computer, I used a game engine like MonoGame, GoDot, and I don’t want to buy Jenny and download a unity to get it.

Jenny probably should be able to buy it in places like Itch.io, not just in the unity store.
Cheers

**Comment by sschmid** [comment]
Hi, yes I was thinking to sell Jenny as a standalone tool. It's really flexible and also works completely without Entitas.
I was thinking to sell it on the Asset Store, because it's convenient and probably most of the people use Unity.
But I'm open to suggestions. I'm not familiar with other stores, so if there are great alternatives, let me know

**Comment by kompyang** [comment]
I think Itch.io is a cool choice. There are not only a lot of cool indie games, but also a lot of independent tools, plugins, text editors, programming languages, art resources, development frameworks, mixers, any Game development related stuff (you can also find an ECS-based console...) https://itch.io/devlogs/tools

I think this is a good way to show Entitas, fully demonstrating the independence of Entitas. You may not be able to anticipate on how many copies it can sell on it, but it is a good way for developers other than used unity to get Jenny.

But this is just my personal suggestion. because I saw a developer asking a similar question on gitter yesterday (and I bought Entitas recently, and the unity's version is updated so frequently today. this is really very 
Tangled, although unity's ECS can't be  production ready now,but it maybe better to use some day.
at least Entitas makes me write very comfortable, I feel very strong under the BDD process, and my heart is very peaceful， i get the follow)

**Comment by kompyang** [comment]
I think Itch.io is a cool choice. There are not only a lot of cool indie games, but also a lot of independent tools, plugins, text editors, programming languages, art resources, development frameworks, mixers, any Game development related stuff (you can also find an ECS-based console...) https://itch.io/devlogs/tools

I think this is a good way to show Entitas, fully demonstrating the independence of Entitas. You may not be able to anticipate on how many copies it can sell on it, but it is a good way for developers other than used unity to get Jenny.

But this is just my personal suggestion. because I saw a developer asking a similar question on gitter yesterday (and I bought Entitas recently, and the unity's version is updated so frequently today. this is really very
Tangled, although unity's ECS can't be production ready now,but it maybe better to use some day.
at least Entitas makes me write very comfortable, I feel very strong under the BDD process, and my heart is very peaceful， i get the follow)

I think this is a good way to show Entitas, fully demonstrating the independence of Entitas. You may not be able to anticipate on how many copies it can sell on it, but it is a good way for developers other than used unity to get Jenny 
.


But this is just my personal suggestion, because I saw a developer asking a similar question on gitter yesterday (and I bought Entitas recently, and the unity's version is updated so frequently today. this is really very

Tangled, although unity's ECS can't be production ready now,  it maybe better to use some day.

At least Entitas makes me write very comfortable, I feel very strong under the BDD process, and my heart is very peaceful)


This is a big job, I think there are too many parts to consider, involving Jenny's development direction, and related protocol issues, at least the licensing agreement I saw in the unity store (except for entita and Roslyn). 
Part) is a plugin for a seat (confused that I didn't know at the outset what is the difference between Entita and github sold in the store)

**Comment by kompyang** [comment]
The following text I use google to translate Chinese into English, I hope you can understand

I think Itch.io is a cool choice. There are not only a lot of cool indie games, but also a lot of independent tools, plugins, text editors, programming languages, art resources, development frameworks, mixers, any Game development related stuff (you can also find an ECS-based console...) https://itch.io/devlogs/tools

I think this is a good way to show Entitas, fully demonstrating the independence of Entitas. You may not be able to anticipate on how many copies it can sell on it, but it is a good way for developers other than used unity to get Jenny.



But this is just my personal suggestion, because I saw a developer asking a similar question on gitter yesterday (and I bought Entitas recently, and the unity's version is updated so frequently today. this is really very

Tangled, although unity's ECS can't be production ready now, it maybe better to use some day.At least Entitas makes me write very comfortable, I feel very strong under the BDD process, and my heart is very peaceful)

but  involving Jenny's positioning , and related protocol issues, at least the licensing agreement I saw in the unity store (except for entita and Roslyn).
Part) is a plugin for a seat (confused that I didn't know at the outset what is the difference between Entita and github sold in the store)

**Comment by zhuchun** [comment]
@sschmid Jenny is a life saver, I use it everyday with Rider, please consider to make it as a standalone tool even without Unity. I've made my own code generator based on T4, but it's far worse than Jenny. It would great if we could customize Jenny, learning Roslyn from scratch is an overkill after all.

**Comment by sschmid** [comment]
You can now build Jenny without getting it from the Asset Store.

Here's a sample Entitas project as a dotnet console app using .NET 6.0 and .NET Standard 2.1, including a working Jenny setup:

[Entitas-Standalone](https://github.com/sschmid/Entitas-Standalone)

Also see announcement: Jenny is now open-source
https://github.com/sschmid/Entitas/discussions/1008
